### ISSUE TITLE
ioremap sometimes too slow

### ISSUE THREAD

**Issue by journey-wang** [kaigai/ssd2gpu#9]
1. use nvidia_p2p_get_page get physical pages
2. use ioremap to map nvidia physical page to kernel virtual address
3. use memcpy_toio copy data from kernel to gpu

Sometimes memcpy_toio too slow, it costs 80ms to transfer  600KB data to gpu.

Please help me!   How to direct access nvidia physical memory from kernel module?

**Comment by kaigai** [comment]
Yes, it's too slow.

Use of AVX register will help you, because it moves wider bits than traditional memcpy().
Probably, best scenario is cuMemCpyHtoD() from the userspace.

I had a discussion with NVIDIA folks to support DMA request from kernel space, but
we could not make a consensus at that time...

**Comment by journey-wang** [comment]
Thanks for your reply, kaigai.

But the problem occurs occasionally,  normally it cost 0.18ms . I cannot figure out the reason why sometimes memcpy_toio so slow.

**Comment by kaigai** [comment]
Hmm. It is different from what I faced in the past. Sorry.

**Comment by journey-wang** [comment]
Hi kaigai
By the way, how did you use nvidia physical pages in nvme-kmod project?  Can nvme kernel module access these pages directly?

**Comment by kaigai** [comment]
We put its physical address on the READ command of NVME, don't use virtual address here.

Linux kernel has API to map physical pages to virtual address. Please look at kmap_atomic(), IIRC.

**Comment by journey-wang** [comment]
Thanks @kaigai

**Comment by journey-wang** [comment]
@kaigai   Depending on your past experience, can you give me some advices on this problem?
When machine boots, it will be either so slow or normal, and will remains until machine reboots.

**Comment by kaigai** [comment]
Sorry, I gave up the approach to move GPU RAM by CPU operations after the discussion with NVIDIA.
So, current kmod does not have the code.
All I could suggest is, 1) use AVX registers for copying, or 2) use userspace API to kick DMA once write back to the userspace. (Here is no reason why kernel space cannot kick DMA (RAM->GPU), however, APIs are not ready for public use. Likely, it's hard to maintain, if possible. )

**Comment by journey-wang** [comment]
Thanks very much @kaigai
